### ISSUE TITLE
Move link list to an "awesome chemical data" repository 

### ISSUE THREAD

**Issue by kjappelbaum** [neo-chem/org#2]
It seems cleaner to me to collect all projects in a dedicated repo similar to the [awesome materials informations](https://github.com/tilde-lab/awesome-materials-informatics)
or [awesome open science](https://github.com/silky/awesome-open-science). 

I can take care of it if you guys thinks it makes sense.﻿

**Comment by ml-evs** [comment]
I think this is a great idea generally and I'd happily contribute! Having a more complete list would be good to emphasize how much a lot of this is a "solved problem" already.

The links I put in this repo were just a few that came up in discussions at the conference, so I don't see any harm in keeping them here for now until we can define the scope of this project/org.

**Comment by kjappelbaum** [comment]
ok, great. Will then later tonight make a repo and add some links.
